### ISSUE TITLE
move Janus.js to npm dependency

### ISSUE THREAD

**Issue by maciej-ka** [apidaze/apidaze-js#13]
Project uses library for WebRTC server Janus.js. This library is embeded in a file `lib/Janus.js`. It would be easier to maintain this as a npm dependency.

<img width="310" alt="Screenshot 2019-04-19 at 08 45 04" src="https://user-images.githubusercontent.com/5403694/56411006-7d0ec780-627f-11e9-8473-bd91cb21e8ef.png">

**Comment by barinali** [comment]
I'm closing this issue as Janus has been recently removed.
