### ISSUE TITLE
generate opaqueid

### ISSUE THREAD

**Issue by maciej-ka** [apidaze/apidaze-js#17]
There is a fixme annotation in `apidaze-js/src/Call.js:257`.

```js
function _attachJanusVideoPlugin(callbackSuccess) {
  var self = this;

  // FIXME: need to figure out how to set opaqueId
  var opaqueId = "videoroomtest-123465464574746";
```

I'm guessing, that intent of author was to replace hardcoded value with generated one.

**Comment by barinali** [comment]
I'm closing this issue as Janus has been recently removed.
