### ISSUE TITLE
Update wsurl value in README

### ISSUE THREAD

**Issue by barinali** [apidaze/apidaze-js#19]
In the sample code below, the given value to `wsurl` property is missing the protocol. Therefore, it's causing an error.

```javascript
const client = new APIdaze.CLIENT({apiKey: "YOUR_API_KEY", wsurl: "fs-us-ny-1.apidaze.io:8082"})
```

We should add `wss` protocol to it as follows;

```javascript
const client = new APIdaze.CLIENT({apiKey: "YOUR_API_KEY", wsurl: "wss://fs-us-ny-1.apidaze.io:8082"})
```

**Comment by maciej-ka** [comment]
I think this can be closed, @barinali
