### ISSUE TITLE
Remove branch from build filenames

### ISSUE THREAD

**Issue by maciej-ka** [apidaze/apidaze-js#21]
Build filenames contain branch in name, for example `APIdaze-3.0.0-dev-feature-branch.js`. The value of this is special, official non master builds, however that potential is not used to my knowledge (and it is probably an add thing compared to other libraries).

However, problem is that sample applications (the ones that integration tests use) expect `APIdaze-latest-dev-master.js` to exist, and at the moment developer has to rename a file after each build.

**Comment by barinali** [comment]
As the associated branch is merged, I am closing this issue. 🎉
