### ISSUE TITLE
[question] sending dial tones

### ISSUE THREAD

**Issue by maciej-ka** [apidaze/apidaze-js#5]
Is it possible to send a dial tone when invocating external script using `apidaze-js` library?

**Comment by maciej-ka** [comment]
Seems it could be possible, here is related fragment in src/Call.js:932 

```
function sendDTMF(digits) {
  LOGGER.log("sendDTMF called, digits : " + digits);
  LOGGER.log("this.callID : " + this.callID);
  var request = {};
  request.wsp_version = "1";
  request.method = "modify";
  request.params = {
    callID: this.callID,
    action: "sendDTMF",
    digits: digits
  };

  this.clientObj._sendMessage(JSON.stringify(request));
}
```

**Comment by barinali** [comment]
@maciej-ka, yes indeed.

After initiating a call, in the call object, we have this method assigned to it. So  I may visualise it in a pseudo way as follows;

```javascript
const call = APIdaze.call(options);
call.sendDTMF('9123');
```

Here, as it can be seen, multiple digits may be passed to `sendDTMF` method.
